---
title: "Practical Nix for Machine Learning"
output: 
  html_document:
    theme: darkly
    toc: true
    toc_float: true
    highlight: kate
---

# WORK IN PROGRESS

THIS BLOG POST ISNT FINISHED!!

In this blog post, we will extend my [previous post](nix.html) on Nix, and show off some tricks which I have found incredibly useful.

# Nix-Shell Shebangs: Fully Isolated, Self Contained Scripts

Here is a scenario which happens to me often: I write a utility script for a project I am working on, forget about it for a while, and then later on realize I can/need to use that script for a new project. This is one thing I didnt like about using virtualenv to manage my python dependencies: I would often have to add the dependencies for the little script to my new project, otherwise there is no verification it will work. 

Nix solves this in a really nice and elegant way: nix-shell shebangs. We can actually make our individual scripts manage their own dependencies, and run in complete isolation, independent of our environment. Below we have a very simple example with a fun, useless script, which we will walk through in depth:

```r
#!/usr/bin/env nix-shell
#! nix-shell -i Rscript -p R rPackages.spongebob
con <- file("stdin")
open(con, blocking=TRUE)
x <- readLines(con)
x <- spongebob::spongebobsay(x)
write(x,"")
```

We will name this file `sponge.R`. Lets test it out:

```{bash}
echo "use nix" | sponge.R
```

It works! Lets walk through the code. First, you specify the interpreter:

```bash
#!/usr/bin/env nix-shell
#! nix-shell -i PUT THE INTERPETER FOR THE SCRIPT HERE
```

The interpreter can be any scripting language you use, be it Rscript, python, perl, bash, whatever you want! Next, you specify the dependencies for the script:


```bash
#!/usr/bin/env nix-shell
#! nix-shell -i PUT THE INTERPETER FOR THE SCRIPT HERE -p DEPENDENCIES HERE
```

`i` stands for interpreter, and `p` stands for packages, and that's it!

# 100% Reproducible, Self-Constained Jupyter Notebooks!


# BUILDING A COMPLEX DEVELOPMENT ENVIRONMENT

# PUTTING IT IN DOCKER

# PRETRAINED MODEL AS A SERVICE

# INTEGRATING CI
